game_type: limit_holdem

lhe_game:
  stack_depth: 20
  num_streets: 2
  max_raises_early: 3
  max_raises_late: 4
  small_bet: 2
  big_bet: 4

# Required by schema but ignored for LHE
game:
  stack_depth: 25
  bet_sizes: [0.5, 1.0]
  max_raises_per_street: 3

deals:
  count: 500000
  seed: 42

training:
  iterations: 500
  traversals_per_iter: 20000
  seed: 42
  output_dir: "./lhe_sdcfr"

network:
  hidden_dim: 128
  num_actions: 3

sgd:
  steps: 20000
  batch_size: 8000
  learning_rate: 0.001

memory:
  advantage_cap: 5000000

checkpoint:
  interval: 1
