game:
  stack_depth: 100
  bet_sizes: [0.33, 0.5, 0.75, 1.0]

abstraction:
  flop_buckets: 200
  turn_buckets: 200
  river_buckets: 500
  samples_per_street: 5000

training:
  iterations: 1000
  seed: 42
  output_dir: "./mccfr_100bb"
  mccfr_samples: 500
  deal_count: 50000
