game:
  stack_depth: 25
  bet_sizes: [0.33, 0.67, 1.0, 2.0, 3.0]
  max_raises_per_street: 3

deals:
  count: 50000
  min_per_class: 100
  max_rejections: 500000
  seed: 42

training:
  iterations: 1500
  traversals_per_iter: 1000
  parallel_traversals: 256
  seed: 42
  output_dir: "./sdcfr_25bb"

network:
  hidden_dim: 256
  num_actions: 8

sgd:
  steps: 4000
  batch_size: 4096
  learning_rate: 0.001
  grad_clip_norm: 1.0

memory:
  advantage_cap: 5000000

checkpoint:
  interval: 100
