pub mod blueprint_ranges;
pub mod domain;
pub mod generate;
#[cfg(feature = "gpu-turn-datagen")]
pub mod gpu_boundary_eval;
pub mod precompute_ranges;
pub mod range_gen;
pub mod sampler;
pub mod solver;
pub mod storage;
