//! Supremus-style GPU preflop auxiliary CFVNet training pipeline.
//!
//! Fundamentally different from the river/turn/flop pipelines -- NO CFR solving.
//! Instead, each training sample is generated by:
//!
//! 1. Sampling a random preflop situation (ranges + pot + stack, no board)
//! 2. Enumerating all C(52,3) = 22,100 possible flops
//! 3. Running a batched forward pass through the trained flop model
//! 4. Averaging the flop model outputs across all flops per combo
//! 5. Inserting the averaged CFVs as training targets
//!
//! The preflop model learns to predict the average flop model output from just
//! ranges + pot + stack (no board information). Its input uses the same 2720-dim
//! format but with board one-hot and rank presence set to all zeros.
//!
//! Pipeline: sample preflop situations -> encode all flops -> flop model inference
//!           -> average across flops -> reservoir insert -> train

#[cfg(feature = "training")]
use std::path::PathBuf;
#[cfg(feature = "training")]
use std::time::Instant;

#[cfg(feature = "training")]
use burn::tensor::backend::AutodiffBackend;

#[cfg(feature = "training")]
use crate::gpu::GpuContext;
#[cfg(feature = "training")]
use crate::training::cuda_net::GpuLeafEvaluatorCuda;
#[cfg(feature = "training")]
use crate::training::reservoir::GpuReservoir;
#[cfg(feature = "training")]
use crate::training::trainer::GpuTrainer;

/// Total number of possible 3-card flops: C(52,3) = 22100.
#[cfg(feature = "training")]
const NUM_FLOPS: u32 = 22100;

/// Configuration for the GPU preflop auxiliary CFVNet training pipeline.
#[cfg(feature = "training")]
#[derive(Debug, Clone)]
pub struct PreflopTrainingConfig {
    /// Path to trained flop model for inference.
    pub flop_model_path: PathBuf,
    /// Number of hidden layers in the flop model (must match trained model).
    pub flop_hidden_layers: usize,
    /// Hidden size of the flop model (must match trained model).
    pub flop_hidden_size: usize,
    /// Total number of training samples to generate.
    pub num_samples: u64,
    /// Maximum capacity of the GPU reservoir buffer.
    pub reservoir_capacity: usize,
    /// Number of hidden layers in the preflop CFVNet.
    pub hidden_layers: usize,
    /// Hidden layer width.
    pub hidden_size: usize,
    /// Mini-batch size for training.
    pub train_batch_size: usize,
    /// Number of training steps per sample batch.
    pub train_steps_per_batch: usize,
    /// Number of spots to process per batch (limited by VRAM).
    pub batch_size: usize,
    /// Initial learning rate.
    pub learning_rate: f64,
    /// Huber loss delta.
    pub huber_delta: f64,
    /// Auxiliary game-value loss weight.
    pub aux_loss_weight: f64,
    /// Print validation metrics every N samples.
    pub validation_interval: u64,
    /// Save checkpoint every N samples.
    pub checkpoint_interval: u64,
    /// Output directory for checkpoints and final model.
    pub output_dir: PathBuf,
    /// Random seed.
    pub seed: u64,
    /// Reference pot size.
    pub ref_pot: i32,
    /// Reference effective stack.
    pub ref_stack: i32,
}

#[cfg(feature = "training")]
impl Default for PreflopTrainingConfig {
    fn default() -> Self {
        Self {
            flop_model_path: PathBuf::from("models/flop_cfvnet/model"),
            flop_hidden_layers: 7,
            flop_hidden_size: 500,
            num_samples: 10_000_000,
            reservoir_capacity: 100_000,
            hidden_layers: 7,
            hidden_size: 500,
            train_batch_size: 1024,
            train_steps_per_batch: 10,
            batch_size: 1,
            learning_rate: 0.001,
            huber_delta: 1.0,
            aux_loss_weight: 1.0,
            validation_interval: 10_000,
            checkpoint_interval: 1_000_000,
            output_dir: PathBuf::from("models/preflop_cfvnet"),
            seed: 42,
            ref_pot: 100,
            ref_stack: 100,
        }
    }
}

/// Per-batch timing accumulator for performance reporting.
#[cfg(feature = "training")]
struct PhaseTiming {
    encode_ms: f64,
    infer_ms: f64,
    average_ms: f64,
    insert_ms: f64,
    train_ms: f64,
}

/// Enumerate all C(52,3) = 22,100 possible 3-card flops.
///
/// Returns a flat array of `[22100 * 3]` u32 card indices.
#[cfg(feature = "training")]
pub fn enumerate_all_flops() -> Vec<u32> {
    let mut flops = Vec::with_capacity(22100 * 3);
    for c1 in 0u32..52 {
        for c2 in (c1 + 1)..52 {
            for c3 in (c2 + 1)..52 {
                flops.push(c1);
                flops.push(c2);
                flops.push(c3);
            }
        }
    }
    assert_eq!(flops.len(), 22100 * 3);
    flops
}

/// Run the GPU preflop auxiliary CFVNet training pipeline.
///
/// Loads the trained flop model, then runs the inference-only loop:
/// sample preflop situations -> enumerate flops -> flop model inference
/// -> average CFVs -> reservoir insert -> train -> validate.
///
/// Each spot produces 22,100 forward pass inputs (one per flop), so memory
/// usage is significant. The `batch_size` parameter controls how many spots
/// are processed simultaneously.
#[cfg(feature = "training")]
pub fn train_preflop_cfvnet_cuda<B: AutodiffBackend>(
    config: &PreflopTrainingConfig,
    device: &B::Device,
) -> Result<(), String> {
    let gpu = GpuContext::new(0).map_err(|e| format!("CUDA init: {e}"))?;

    // 1. Load flop model using CUDA-native inference
    eprintln!(
        "Loading flop model from {:?} ({}x{}) with CUDA-native inference...",
        config.flop_model_path, config.flop_hidden_layers, config.flop_hidden_size
    );

    // Max batch size for flop model inference:
    // 22100 flops * batch_size spots per forward pass.
    let max_infer_batch = NUM_FLOPS as usize * config.batch_size;
    let mut flop_model = GpuLeafEvaluatorCuda::load(
        &config.flop_model_path,
        &gpu,
        config.flop_hidden_layers,
        config.flop_hidden_size,
        max_infer_batch,
    )?;

    // 2. Pre-enumerate all 22,100 flops and upload to GPU
    let all_flops_cpu = enumerate_all_flops();
    let gpu_all_flops = gpu
        .upload(&all_flops_cpu)
        .map_err(|e| format!("upload flops: {e}"))?;

    // Upload combo cards lookup
    let combo_cards_flat = crate::training::hand_eval::build_combo_cards_flat();
    let gpu_combo_cards = gpu
        .upload(&combo_cards_flat)
        .map_err(|e| format!("upload combo cards: {e}"))?;

    // 3. Initialize components
    let mut reservoir = GpuReservoir::new(&gpu, config.reservoir_capacity)
        .map_err(|e| format!("reservoir: {e}"))?;
    let mut trainer = GpuTrainer::<B>::new(
        device,
        config.hidden_layers,
        config.hidden_size,
        config.learning_rate,
        config.huber_delta,
        config.aux_loss_weight,
    );

    // Pre-allocate working buffers for encoding + inference + averaging.
    // Per spot: 22100 inputs x 2720 = 240MB, 22100 x 1326 = 117MB.
    // With batch_size spots: multiply by batch_size.
    let total_inputs = NUM_FLOPS as usize * config.batch_size;
    let mut encoded_buf = gpu
        .alloc_zeros::<f32>(total_inputs * 2720)
        .map_err(|e| format!("alloc encoded: {e}"))?;
    // Pre-allocate pot/stack buffers for encoding
    let pots = vec![config.ref_pot as f32; config.batch_size];
    let stacks = vec![config.ref_stack as f32; config.batch_size];
    let gpu_pots = gpu.upload(&pots).map_err(|e| format!("upload pots: {e}"))?;
    let gpu_stacks = gpu.upload(&stacks).map_err(|e| format!("upload stacks: {e}"))?;

    // For reservoir insertion, we need "boards" -- preflop has no board,
    // so use dummy boards (all 255) which the reservoir kernel ignores.
    let dummy_boards = vec![255u32; config.batch_size * 5];
    let gpu_dummy_boards = gpu
        .upload(&dummy_boards)
        .map_err(|e| format!("upload dummy boards: {e}"))?;

    // Generate uniform ranges for sampling (all combos at weight 1.0)
    let uniform_range = vec![1.0f32; config.batch_size * 1326];
    let gpu_ranges_oop = gpu
        .upload(&uniform_range)
        .map_err(|e| format!("upload ranges oop: {e}"))?;
    let gpu_ranges_ip = gpu
        .upload(&uniform_range)
        .map_err(|e| format!("upload ranges ip: {e}"))?;

    let mut total_samples = 0u64;
    let mut last_loss = f32::MAX;
    let mut sample_seed = config.seed + 2_000_000;
    let start = Instant::now();

    let mut timing_accum = PhaseTiming {
        encode_ms: 0.0,
        infer_ms: 0.0,
        average_ms: 0.0,
        insert_ms: 0.0,
        train_ms: 0.0,
    };
    let mut batches_since_report = 0u64;

    std::fs::create_dir_all(&config.output_dir)
        .map_err(|e| format!("create output dir: {e}"))?;

    eprintln!("Starting GPU preflop training pipeline (inference-only)");
    eprintln!("  Batch size: {} spots", config.batch_size);
    eprintln!("  Flops per spot: {}", NUM_FLOPS);
    eprintln!(
        "  Total inputs per batch: {} ({}x{})",
        total_inputs, NUM_FLOPS, config.batch_size
    );
    eprintln!("  Reservoir capacity: {}", config.reservoir_capacity);
    eprintln!(
        "  Preflop model: {} layers x {} hidden",
        config.hidden_layers, config.hidden_size
    );
    eprintln!(
        "  Flop model: {} layers x {} hidden",
        config.flop_hidden_layers, config.flop_hidden_size
    );
    eprintln!("  Inference: CUDA-native (cuBLAS + custom kernels)");
    eprintln!(
        "  Train batch: {} x {} steps/batch",
        config.train_batch_size, config.train_steps_per_batch
    );
    eprintln!("  Learning rate: {}", config.learning_rate);
    eprintln!("  Output: {}", config.output_dir.display());
    eprintln!();

    while total_samples < config.num_samples {
        let t0 = Instant::now();

        // === OOP: Encode + Infer + Average ===
        gpu.launch_encode_preflop_inputs(
            &mut encoded_buf,
            &gpu_ranges_oop,
            &gpu_ranges_ip,
            &gpu_all_flops,
            &gpu_combo_cards,
            &gpu_pots,
            &gpu_stacks,
            0, // OOP traverser
            NUM_FLOPS,
            config.batch_size as u32,
        )
        .map_err(|e| format!("encode OOP: {e}"))?;

        let raw_cfvs_oop = flop_model
            .infer(&gpu, &encoded_buf, total_inputs)
            .map_err(|e| format!("infer OOP: {e}"))?;

        let mut avg_cfvs_oop = gpu
            .alloc_zeros::<f32>(config.batch_size * 1326)
            .map_err(|e| format!("alloc oop: {e}"))?;
        gpu.launch_average_preflop_cfvs(
            &mut avg_cfvs_oop,
            &raw_cfvs_oop,
            &gpu_all_flops,
            &gpu_combo_cards,
            NUM_FLOPS,
            config.batch_size as u32,
        )
        .map_err(|e| format!("average OOP: {e}"))?;

        let t1 = Instant::now();

        // === IP: Encode + Infer + Average ===
        gpu.launch_encode_preflop_inputs(
            &mut encoded_buf,
            &gpu_ranges_oop,
            &gpu_ranges_ip,
            &gpu_all_flops,
            &gpu_combo_cards,
            &gpu_pots,
            &gpu_stacks,
            1, // IP traverser
            NUM_FLOPS,
            config.batch_size as u32,
        )
        .map_err(|e| format!("encode IP: {e}"))?;

        let raw_cfvs_ip = flop_model
            .infer(&gpu, &encoded_buf, total_inputs)
            .map_err(|e| format!("infer IP: {e}"))?;

        let mut avg_cfvs_ip = gpu
            .alloc_zeros::<f32>(config.batch_size * 1326)
            .map_err(|e| format!("alloc ip: {e}"))?;
        gpu.launch_average_preflop_cfvs(
            &mut avg_cfvs_ip,
            &raw_cfvs_ip,
            &gpu_all_flops,
            &gpu_combo_cards,
            NUM_FLOPS,
            config.batch_size as u32,
        )
        .map_err(|e| format!("average IP: {e}"))?;

        let t2 = Instant::now();

        // === INSERT: Both OOP and IP into reservoir ===
        reservoir
            .insert_batch_gpu(
                &gpu,
                &gpu_ranges_oop,
                &gpu_ranges_ip,
                &gpu_dummy_boards,
                &gpu_pots,
                &gpu_stacks,
                &avg_cfvs_oop,
                &avg_cfvs_ip,
                config.batch_size,
            )
            .map_err(|e| format!("reservoir insert: {e}"))?;
        let t3 = Instant::now();

        // Timing: split OOP/IP encode+infer+avg equally
        let per_traverser = ((t1 - t0).as_secs_f64() + (t2 - t1).as_secs_f64()) * 1000.0;
        timing_accum.encode_ms += per_traverser * 0.2;  // rough split
        timing_accum.infer_ms += per_traverser * 0.7;
        timing_accum.average_ms += per_traverser * 0.1;
        timing_accum.insert_ms += (t3 - t2).as_secs_f64() * 1000.0;

        total_samples += (config.batch_size as u64) * 2; // 2 records per spot

        // === TRAIN PHASE ===
        let t_train_start = Instant::now();
        if reservoir.size() >= config.train_batch_size {
            for _ in 0..config.train_steps_per_batch {
                sample_seed += 1;
                let batch = reservoir
                    .sample_minibatch_gpu(
                        &gpu,
                        config.train_batch_size,
                        sample_seed as u32,
                    )
                    .map_err(|e| format!("sample minibatch: {e}"))?;

                last_loss = trainer.train_step(&gpu, &batch)?;
            }
        }
        let t_train_end = Instant::now();
        timing_accum.train_ms += (t_train_end - t_train_start).as_secs_f64() * 1000.0;
        batches_since_report += 1;

        // === VALIDATION ===
        if total_samples % config.validation_interval < (config.batch_size as u64 * 2) {
            let elapsed = start.elapsed().as_secs_f64();
            let rate = total_samples as f64 / elapsed;

            let val_loss = if reservoir.size() >= config.train_batch_size {
                sample_seed += 1;
                let val_batch = reservoir
                    .sample_minibatch_gpu(
                        &gpu,
                        config.train_batch_size,
                        sample_seed as u32,
                    )
                    .map_err(|e| format!("val batch: {e}"))?;
                trainer.validation_loss(&gpu, &val_batch)?
            } else {
                f32::NAN
            };

            eprintln!(
                "[{:>12} samples] loss={:.6} val={:.6} rate={:.0} samples/s  reservoir={}",
                total_samples, last_loss, val_loss, rate, reservoir.size()
            );

            if batches_since_report > 0 {
                let n = batches_since_report as f64;
                eprintln!(
                    "  timing: encode={:.1}ms infer={:.1}ms avg={:.1}ms insert={:.1}ms train={:.1}ms  ({} batches avg)",
                    timing_accum.encode_ms / n,
                    timing_accum.infer_ms / n,
                    timing_accum.average_ms / n,
                    timing_accum.insert_ms / n,
                    timing_accum.train_ms / n,
                    batches_since_report,
                );
            }

            timing_accum = PhaseTiming {
                encode_ms: 0.0,
                infer_ms: 0.0,
                average_ms: 0.0,
                insert_ms: 0.0,
                train_ms: 0.0,
            };
            batches_since_report = 0;
        }

        // === CHECKPOINT ===
        if config.checkpoint_interval > 0
            && total_samples % config.checkpoint_interval < (config.batch_size as u64 * 2)
            && total_samples > 0
        {
            let label = format!("checkpoint_{}", total_samples);
            trainer.save_checkpoint(&config.output_dir, &label);
            eprintln!("  Saved checkpoint: {}", label);
        }
    }

    trainer.save_final(&config.output_dir)?;
    let elapsed = start.elapsed().as_secs_f64();
    eprintln!();
    eprintln!(
        "Preflop training complete (inference-only). {} samples in {:.1}s ({:.0} samples/s)",
        total_samples,
        elapsed,
        total_samples as f64 / elapsed
    );
    eprintln!("Model saved to {:?}", config.output_dir);
    Ok(())
}

#[cfg(all(test, feature = "training"))]
mod tests {
    use super::*;

    #[test]
    fn test_preflop_pipeline_config_defaults() {
        let config = PreflopTrainingConfig::default();
        assert_eq!(config.batch_size, 1);
        assert_eq!(config.reservoir_capacity, 100_000);
        assert_eq!(config.flop_hidden_layers, 7);
        assert_eq!(config.flop_hidden_size, 500);
    }

    #[test]
    fn test_enumerate_all_flops() {
        let flops = enumerate_all_flops();
        assert_eq!(flops.len(), 22100 * 3);

        // First flop should be (0, 1, 2)
        assert_eq!(flops[0], 0);
        assert_eq!(flops[1], 1);
        assert_eq!(flops[2], 2);

        // Last flop should be (49, 50, 51)
        let last = flops.len() - 3;
        assert_eq!(flops[last], 49);
        assert_eq!(flops[last + 1], 50);
        assert_eq!(flops[last + 2], 51);

        // All cards should be < 52
        for &c in &flops {
            assert!(c < 52, "card {} should be < 52", c);
        }

        // Each triple should be sorted (c1 < c2 < c3)
        for i in 0..22100 {
            let c1 = flops[i * 3];
            let c2 = flops[i * 3 + 1];
            let c3 = flops[i * 3 + 2];
            assert!(c1 < c2 && c2 < c3, "flop {} not sorted: ({}, {}, {})", i, c1, c2, c3);
        }
    }
}
