//! Game tree construction helpers.
//!
//! Extracted from `turn_generate.rs` so the domain pipeline can use them
//! without depending on the old monolithic datagen module.

use poker_solver_core::poker::{Card, Suit, Value};
use rand::Rng;
use range_solver::action_tree::{ActionTree, BoardState, TreeConfig};
use range_solver::bet_size::{BetSize, BetSizeOptions};
use range_solver::card::{CardConfig, NOT_DEALT};
use range_solver::game::PostFlopGame;
use range_solver::range::Range as RsRange;

use crate::config::BetSizeConfig;
use crate::datagen::range_gen::NUM_COMBOS;

/// Convert a range-solver `u8` card to an `rs_poker::core::Card`.
pub fn u8_to_rs_card(id: u8) -> Card {
    let rank = id / 4;
    let suit_id = id % 4;
    let value = Value::from(rank);
    let suit = match suit_id {
        0 => Suit::Club,
        1 => Suit::Diamond,
        2 => Suit::Heart,
        3 => Suit::Spade,
        _ => unreachable!(),
    };
    Card::new(value, suit)
}

/// Parse a single depth's bet size strings (e.g. `["50%", "100%", "a"]`) into bet sizes.
///
/// Explicit "a"/"A" entries are preserved as `BetSize::AllIn`. They are not
/// generated by all-in thresholds in this domain path because those thresholds
/// are disabled for stable datagen topology.
fn parse_bet_sizes_depth(sizes: &[String]) -> Vec<BetSize> {
    sizes
        .iter()
        .filter_map(|s| {
            let trimmed = s.trim();
            if trimmed.eq_ignore_ascii_case("a") {
                return Some(BetSize::AllIn);
            }
            let num_str = trimmed.trim_end_matches('%');
            num_str
                .parse::<f64>()
                .ok()
                .map(|v| BetSize::PotRelative(v / 100.0))
        })
        .collect()
}

/// Parse all depths from a BetSizeConfig into `Vec<Vec<BetSize>>`.
pub fn parse_bet_sizes_all(config: &BetSizeConfig) -> Vec<Vec<BetSize>> {
    config
        .depths()
        .iter()
        .map(|d| parse_bet_sizes_depth(d))
        .collect()
}

/// Perturb bet sizes by multiplying each by `1.0 + uniform(-fuzz, +fuzz)`.
///
/// Returns the original sizes unchanged if `fuzz <= 0.0`.
/// Each fuzzed value is clamped to a minimum of 0.01 to avoid non-positive sizes.
pub fn fuzz_bet_sizes(
    bet_sizes: &[Vec<BetSize>],
    fuzz: f64,
    rng: &mut impl Rng,
) -> Vec<Vec<BetSize>> {
    if fuzz <= 0.0 {
        return bet_sizes.to_vec();
    }
    bet_sizes
        .iter()
        .map(|depth| {
            depth
                .iter()
                .map(|&size| match size {
                    BetSize::PotRelative(fraction) => {
                        let perturbation = 1.0 + rng.gen_range(-fuzz..fuzz);
                        BetSize::PotRelative((fraction * perturbation).max(0.01))
                    }
                    other => other,
                })
                .collect()
        })
        .collect()
}

/// Build a turn game tree for a situation.
///
/// When `exact` is false (model mode): uses `depth_limit: Some(0)` to create boundary
/// nodes at the river transition, with empty river bet sizes.
/// When `exact` is true: uses `depth_limit: None` so the tree extends through the
/// river to showdown, with river bet sizes matching turn sizes.
///
/// Returns `None` for degenerate situations (effective_stack <= 0, or game construction fails).
fn build_turn_game_inner(
    board_u8: &[u8],
    pot: f64,
    effective_stack: f64,
    ranges: &[[f32; NUM_COMBOS]; 2],
    bet_sizes: &[Vec<BetSize>],
    exact: bool,
) -> Option<PostFlopGame> {
    let oop_range = RsRange::from_raw_data(&ranges[0]).expect("valid OOP range");
    let ip_range = RsRange::from_raw_data(&ranges[1]).expect("valid IP range");

    // bet_sizes rows are keyed by the number of bets already made on this street:
    // row 0 = first bet, row 1 = second bet / first raise, and so on. After the
    // last configured row, range-solver forces all-in-only raises.
    let bet = bet_sizes.first().map(|v| v.to_vec()).unwrap_or_default();
    let raise = bet_sizes.get(1).map_or_else(Vec::new, Vec::clone);
    let bet_size_opts = BetSizeOptions {
        bet,
        raise,
        per_num_bets: bet_sizes.to_vec(),
    };

    let is_river = board_u8.len() >= 5;

    let card_config = CardConfig {
        range: [oop_range, ip_range],
        flop: [board_u8[0], board_u8[1], board_u8[2]],
        turn: board_u8[3],
        river: if is_river { board_u8[4] } else { NOT_DEALT },
    };

    let (river_bet_sizes, depth_limit) = if exact || is_river {
        ([bet_size_opts.clone(), bet_size_opts.clone()], None)
    } else {
        (
            [BetSizeOptions::default(), BetSizeOptions::default()],
            Some(0),
        )
    };

    let initial_state = if is_river {
        BoardState::River
    } else {
        BoardState::Turn
    };

    let tree_config = TreeConfig {
        initial_state,
        starting_pot: pot as i32,
        effective_stack: effective_stack as i32,
        turn_bet_sizes: [bet_size_opts.clone(), bet_size_opts],
        river_bet_sizes,
        depth_limit,
        add_allin_threshold: 0.0,
        force_allin_threshold: 0.0,
        merging_threshold: 0.0,
        ..Default::default()
    };

    let action_tree = ActionTree::new(tree_config).expect("valid action tree");
    let mut game = PostFlopGame::with_config(card_config, action_tree).expect("valid game");
    game.allocate_memory(true); // compressed (16-bit) storage to reduce memory ~4x
    use std::sync::atomic::{AtomicBool, Ordering as AO};
    static LOGGED: AtomicBool = AtomicBool::new(false);
    if !LOGGED.swap(true, AO::Relaxed) {
        let (mem, _) = game.memory_usage();
        eprintln!("[tree] memory per game: {:.1} MB", mem as f64 / 1_048_576.0);
    }
    Some(game)
}

fn build_flop_game_inner(
    board_u8: &[u8],
    pot: f64,
    effective_stack: f64,
    ranges: &[[f32; NUM_COMBOS]; 2],
    bet_sizes: &[Vec<BetSize>],
    exact: bool,
) -> Option<PostFlopGame> {
    if board_u8.len() != 3 {
        return None;
    }

    let oop_range = RsRange::from_raw_data(&ranges[0]).expect("valid OOP range");
    let ip_range = RsRange::from_raw_data(&ranges[1]).expect("valid IP range");

    let bet = bet_sizes.first().map(|v| v.to_vec()).unwrap_or_default();
    let raise = bet_sizes.get(1).map_or_else(Vec::new, Vec::clone);
    let bet_size_opts = BetSizeOptions {
        bet,
        raise,
        per_num_bets: bet_sizes.to_vec(),
    };

    let card_config = CardConfig {
        range: [oop_range, ip_range],
        flop: [board_u8[0], board_u8[1], board_u8[2]],
        turn: NOT_DEALT,
        river: NOT_DEALT,
    };

    let (river_bet_sizes, depth_limit) = if exact {
        ([bet_size_opts.clone(), bet_size_opts.clone()], None)
    } else {
        (
            [BetSizeOptions::default(), BetSizeOptions::default()],
            Some(1),
        )
    };

    let tree_config = TreeConfig {
        initial_state: BoardState::Flop,
        starting_pot: pot as i32,
        effective_stack: effective_stack as i32,
        flop_bet_sizes: [bet_size_opts.clone(), bet_size_opts.clone()],
        turn_bet_sizes: [bet_size_opts.clone(), bet_size_opts],
        river_bet_sizes,
        depth_limit,
        add_allin_threshold: 0.0,
        force_allin_threshold: 0.0,
        merging_threshold: 0.0,
        ..Default::default()
    };

    let action_tree = ActionTree::new(tree_config).expect("valid action tree");
    let mut game = PostFlopGame::with_config(card_config, action_tree).expect("valid game");
    game.allocate_memory(true);
    Some(game)
}

/// Build a depth-limited turn game tree (model mode, with boundary nodes at river).
pub fn build_turn_game(
    board_u8: &[u8],
    pot: f64,
    effective_stack: f64,
    ranges: &[[f32; NUM_COMBOS]; 2],
    bet_sizes: &[Vec<BetSize>],
) -> Option<PostFlopGame> {
    build_turn_game_inner(board_u8, pot, effective_stack, ranges, bet_sizes, false)
}

/// Build a full turn+river game tree (exact mode, no boundaries).
pub fn build_turn_game_exact(
    board_u8: &[u8],
    pot: f64,
    effective_stack: f64,
    ranges: &[[f32; NUM_COMBOS]; 2],
    bet_sizes: &[Vec<BetSize>],
) -> Option<PostFlopGame> {
    build_turn_game_inner(board_u8, pot, effective_stack, ranges, bet_sizes, true)
}

/// Build a depth-limited flop game tree with 4-card turn boundary nodes.
pub fn build_flop_game(
    board_u8: &[u8],
    pot: f64,
    effective_stack: f64,
    ranges: &[[f32; NUM_COMBOS]; 2],
    bet_sizes: &[Vec<BetSize>],
) -> Option<PostFlopGame> {
    build_flop_game_inner(board_u8, pot, effective_stack, ranges, bet_sizes, false)
}

/// Build a full flop+turn+river game tree.
pub fn build_flop_game_exact(
    board_u8: &[u8],
    pot: f64,
    effective_stack: f64,
    ranges: &[[f32; NUM_COMBOS]; 2],
    bet_sizes: &[Vec<BetSize>],
) -> Option<PostFlopGame> {
    build_flop_game_inner(board_u8, pot, effective_stack, ranges, bet_sizes, true)
}

/// Build a canonical (maximum-SPR) turn tree for batched datagen.
///
/// Uses a fixed non-conflicting board, `pot=100`, `effective_stack=10_000`
/// (SPR=100, so no bet size collapses to all-in), and uniform ranges across
/// all non-board-conflicting hand pairs. The resulting `PostFlopGame` has a
/// depth-limited tree (boundary nodes at the river transition) whose
/// topology is structurally identical to what every turn situation with the
/// same bet sizes would produce at sufficiently deep effective stack.
///
/// The canonical game is intended for one-shot topology extraction; per-game
/// data (pot-scaled fold payoffs, initial weights with board blockers, etc.)
/// is supplied through `SubgameSpec` at `prepare_batch` time.
///
/// Returns `None` if the canonical tree fails to build (e.g. empty bet sizes).
pub fn build_canonical_turn_tree(bet_sizes: &[Vec<BetSize>]) -> Option<PostFlopGame> {
    // Arbitrary non-conflicting board. Card ids: 0=2c, 4=3c, 8=4c, 12=5c.
    let board: [u8; 4] = [0, 4, 8, 12];
    let pot = 100.0_f64;
    let effective_stack = 10_000.0_f64; // SPR=100

    // Uniform ranges over every non-board-conflicting hand pair.
    let mut ranges = [[0.0_f32; NUM_COMBOS]; 2];
    let board_mask: u64 =
        (1u64 << board[0]) | (1u64 << board[1]) | (1u64 << board[2]) | (1u64 << board[3]);
    for c0 in 0u8..52 {
        for c1 in (c0 + 1)..52 {
            let hand_mask = (1u64 << c0) | (1u64 << c1);
            if hand_mask & board_mask != 0 {
                continue;
            }
            let idx = range_solver::card::card_pair_to_index(c0, c1);
            ranges[0][idx] = 1.0;
            ranges[1][idx] = 1.0;
        }
    }

    build_turn_game(&board, pot, effective_stack, &ranges, bet_sizes)
}

#[cfg(test)]
mod tests {
    use super::*;
    use range_solver::action_tree::Action;

    fn pot(size: f64) -> BetSize {
        BetSize::PotRelative(size)
    }

    #[test]
    fn u8_to_rs_card_converts_correctly() {
        // Card 0 = 2 of Clubs (rank=0, suit=0)
        let card = u8_to_rs_card(0);
        assert_eq!(card.value, Value::Two);
        assert_eq!(card.suit, Suit::Club);

        // Card 1 = 2 of Diamonds (rank=0, suit=1)
        let card = u8_to_rs_card(1);
        assert_eq!(card.value, Value::Two);
        assert_eq!(card.suit, Suit::Diamond);

        // Card 51 = Ace of Spades (rank=12, suit=3)
        let card = u8_to_rs_card(51);
        assert_eq!(card.value, Value::Ace);
        assert_eq!(card.suit, Suit::Spade);
    }

    #[test]
    fn parse_bet_sizes_depth_parses_percentages() {
        let sizes = vec!["50%".into(), "100%".into()];
        let parsed = parse_bet_sizes_depth(&sizes);
        assert_eq!(parsed.len(), 2);
        assert_eq!(parsed[0], pot(0.5));
        assert_eq!(parsed[1], pot(1.0));
    }

    #[test]
    fn parse_bet_sizes_depth_preserves_allin() {
        let sizes = vec!["50%".into(), "a".into(), "100%".into()];
        let parsed = parse_bet_sizes_depth(&sizes);
        assert_eq!(parsed, vec![pot(0.5), BetSize::AllIn, pot(1.0)]);
    }

    #[test]
    fn parse_bet_sizes_depth_preserves_allin_case_insensitive() {
        let sizes = vec!["A".into(), "50%".into()];
        let parsed = parse_bet_sizes_depth(&sizes);
        assert_eq!(parsed, vec![BetSize::AllIn, pot(0.5)]);
    }

    #[test]
    fn parse_bet_sizes_depth_handles_empty() {
        let sizes: Vec<String> = vec![];
        let parsed = parse_bet_sizes_depth(&sizes);
        assert!(parsed.is_empty());
    }

    #[test]
    fn fuzz_bet_sizes_noop_when_zero() {
        let sizes = vec![vec![pot(0.5), pot(1.0), BetSize::AllIn]];
        let mut rng = rand::thread_rng();
        let result = fuzz_bet_sizes(&sizes, 0.0, &mut rng);
        assert_eq!(result, sizes);
    }

    #[test]
    fn fuzz_bet_sizes_noop_when_negative() {
        let sizes = vec![vec![pot(0.5), pot(1.0), BetSize::AllIn]];
        let mut rng = rand::thread_rng();
        let result = fuzz_bet_sizes(&sizes, -0.1, &mut rng);
        assert_eq!(result, sizes);
    }

    #[test]
    fn fuzz_bet_sizes_perturbs_values() {
        use rand::SeedableRng;
        use rand_chacha::ChaCha8Rng;

        let sizes = vec![vec![pot(0.5), pot(1.0)]];
        let mut rng = ChaCha8Rng::seed_from_u64(42);
        let result = fuzz_bet_sizes(&sizes, 0.2, &mut rng);
        assert_eq!(result.len(), 1);
        assert_eq!(result[0].len(), 2);
        let BetSize::PotRelative(first) = result[0][0] else {
            panic!("first size should remain pot-relative");
        };
        let BetSize::PotRelative(second) = result[0][1] else {
            panic!("second size should remain pot-relative");
        };
        // Values should be perturbed but within 20% of original.
        assert!((first - 0.5).abs() < 0.5 * 0.2 + 0.01);
        assert!((second - 1.0).abs() < 1.0 * 0.2 + 0.01);
    }

    #[test]
    fn fuzz_bet_sizes_preserves_allin() {
        use rand::SeedableRng;
        use rand_chacha::ChaCha8Rng;

        let sizes = vec![
            vec![pot(0.5), BetSize::AllIn],
            vec![pot(0.75), BetSize::AllIn],
        ];
        let mut rng = ChaCha8Rng::seed_from_u64(42);
        let result = fuzz_bet_sizes(&sizes, 0.2, &mut rng);

        assert_eq!(result[0][1], BetSize::AllIn);
        assert_eq!(result[1][1], BetSize::AllIn);
    }

    #[test]
    fn fuzz_bet_sizes_clamps_minimum() {
        use rand::SeedableRng;
        use rand_chacha::ChaCha8Rng;

        let sizes = vec![vec![pot(0.001)]]; // Very small value
        let mut rng = ChaCha8Rng::seed_from_u64(42);
        let result = fuzz_bet_sizes(&sizes, 0.99, &mut rng);
        let BetSize::PotRelative(size) = result[0][0] else {
            panic!("size should remain pot-relative");
        };
        assert!(size >= 0.01, "should clamp to minimum 0.01");
    }

    #[test]
    fn flop_depth_limited_tree_has_four_card_turn_boundaries() {
        let board = [0, 4, 8];
        let ranges = [[1.0_f32; NUM_COMBOS]; 2];
        let sizes = vec![vec![pot(0.5)], vec![BetSize::AllIn]];

        let game = build_flop_game(&board, 100.0, 1_000.0, &ranges, &sizes)
            .expect("flop depth-limited tree should build");
        let boards = game.boundary_boards();

        assert!(!boards.is_empty(), "flop tree should expose boundaries");
        assert_eq!(boards.len(), game.num_boundary_nodes());
        for boundary_board in boards {
            assert_eq!(boundary_board.len(), 4);
            assert_eq!(&boundary_board[..3], &board);
            assert!(!board.contains(&boundary_board[3]));
        }
    }

    #[test]
    fn river_exact_tree_with_explicit_allin_exposes_allin_action() {
        let board = [0, 4, 8, 12, 16];
        let ranges = [[1.0_f32; NUM_COMBOS]; 2];
        let sizes = vec![vec![pot(0.5), BetSize::AllIn]];

        let game = build_turn_game_exact(&board, 100.0, 1_000.0, &ranges, &sizes)
            .expect("river exact tree should build");
        let actions = game.available_actions();

        assert!(
            actions.contains(&Action::AllIn(1_000)),
            "explicit all-in should be present with thresholds disabled: {actions:?}"
        );
    }

    #[test]
    fn river_exact_raise_node_with_explicit_allin_exposes_allin_action() {
        let board = [0, 4, 8, 12, 16];
        let ranges = [[1.0_f32; NUM_COMBOS]; 2];
        let sizes = vec![vec![pot(0.5)], vec![pot(0.75), BetSize::AllIn]];

        let mut game = build_turn_game_exact(&board, 100.0, 1_000.0, &ranges, &sizes)
            .expect("river exact tree should build");
        let root_actions = game.available_actions();
        let bet_index = root_actions
            .iter()
            .position(|action| matches!(action, Action::Bet(_)))
            .expect("root should expose a first bet");

        game.play(bet_index);
        let raise_actions = game.available_actions();

        assert!(
            raise_actions.contains(&Action::AllIn(1_000)),
            "explicit all-in raise should be present with thresholds disabled: {raise_actions:?}"
        );
    }

    #[test]
    fn river_exact_per_round_rows_restrict_third_bet_to_allin() {
        let board = [0, 4, 8, 12, 16];
        let ranges = [[1.0_f32; NUM_COMBOS]; 2];
        let sizes = vec![vec![pot(0.5)], vec![pot(0.75)], vec![BetSize::AllIn]];

        let mut game = build_turn_game_exact(&board, 100.0, 1_000.0, &ranges, &sizes)
            .expect("river exact tree should build");

        let root_bet_index = game
            .available_actions()
            .iter()
            .position(|action| matches!(action, Action::Bet(_)))
            .expect("root should expose a first bet");
        game.play(root_bet_index);

        let second_bet_index = game
            .available_actions()
            .iter()
            .position(|action| matches!(action, Action::Raise(_)))
            .expect("second bet should expose a non-all-in raise");
        game.play(second_bet_index);

        let third_bet_actions = game.available_actions();
        assert!(
            third_bet_actions.contains(&Action::AllIn(1_000)),
            "third bet should expose all-in: {third_bet_actions:?}"
        );
        assert!(
            !third_bet_actions
                .iter()
                .any(|action| matches!(action, Action::Raise(_))),
            "third bet should not expose non-all-in raises: {third_bet_actions:?}"
        );
    }

    #[test]
    fn river_exact_per_round_rows_force_allin_after_last_configured_row() {
        let board = [0, 4, 8, 12, 16];
        let ranges = [[1.0_f32; NUM_COMBOS]; 2];
        let sizes = vec![
            vec![pot(0.1)],
            vec![pot(0.1)],
            vec![pot(0.1)],
            vec![pot(0.1)],
            vec![pot(0.1)],
        ];

        let mut game = build_turn_game_exact(&board, 100.0, 1_000_000.0, &ranges, &sizes)
            .expect("river exact tree should build");

        let first_bet_index = game
            .available_actions()
            .iter()
            .position(|action| matches!(action, Action::Bet(_)))
            .expect("first row should expose a non-all-in bet");
        game.play(first_bet_index);

        for round in 1..=4 {
            let actions = game.available_actions();
            let raise_index = actions
                .iter()
                .position(|action| matches!(action, Action::Raise(_)))
                .unwrap_or_else(|| {
                    panic!("row {round} should expose a non-all-in raise: {actions:?}")
                });
            game.play(raise_index);
        }

        let forced_actions = game.available_actions();
        assert!(
            forced_actions.contains(&Action::AllIn(1_000_000)),
            "beyond configured rows should expose all-in: {forced_actions:?}"
        );
        assert!(
            !forced_actions
                .iter()
                .any(|action| matches!(action, Action::Raise(_))),
            "beyond configured rows should not expose non-all-in raises: {forced_actions:?}"
        );
    }
}
